//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVAppMobile.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CVAppMobile.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Experiencia.
        /// </summary>
        internal static string ExperienceTabbed {
            get {
                return ResourceManager.GetString("ExperienceTabbed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargando....
        /// </summary>
        internal static string GenericLoadingIndicator {
            get {
                return ResourceManager.GetString("GenericLoadingIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        internal static string HomeTabbed {
            get {
                return ResourceManager.GetString("HomeTabbed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Soltero.
        /// </summary>
        internal static string LabelCivilStatus {
            get {
                return ResourceManager.GetString("LabelCivilStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puebla, México.
        /// </summary>
        internal static string LabelCurrentResidence {
            get {
                return ResourceManager.GetString("LabelCurrentResidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a david_pleo@hotmail.com.
        /// </summary>
        internal static string LabelEmail {
            get {
                return ResourceManager.GetString("LabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a de experiencia.
        /// </summary>
        internal static string LabelExperience {
            get {
                return ResourceManager.GetString("LabelExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No. G31323557.
        /// </summary>
        internal static string LabelPassport {
            get {
                return ResourceManager.GetString("LabelPassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos personales.
        /// </summary>
        internal static string LabelPersonalData {
            get {
                return ResourceManager.GetString("LabelPersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 22-23-46-42-50.
        /// </summary>
        internal static string LabelPoneNumber {
            get {
                return ResourceManager.GetString("LabelPoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puebla.
        /// </summary>
        internal static string LabelPuebla {
            get {
                return ResourceManager.GetString("LabelPuebla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a JUAD930604K37.
        /// </summary>
        internal static string LabelRfc {
            get {
                return ResourceManager.GetString("LabelRfc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 6 años.
        /// </summary>
        internal static string LabelSixYears {
            get {
                return ResourceManager.GetString("LabelSixYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a David Juarez Avila.
        /// </summary>
        internal static string LabelUserName {
            get {
                return ResourceManager.GetString("LabelUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vigente.
        /// </summary>
        internal static string LabelVisa {
            get {
                return ResourceManager.GetString("LabelVisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desarrollador de Software.
        /// </summary>
        internal static string LabelWorkStation {
            get {
                return ResourceManager.GetString("LabelWorkStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 31 años.
        /// </summary>
        internal static string LabelYearsOld {
            get {
                return ResourceManager.GetString("LabelYearsOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        internal static string LanguageSpanish {
            get {
                return ResourceManager.GetString("LanguageSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyectos.
        /// </summary>
        internal static string ProjectsTabbed {
            get {
                return ResourceManager.GetString("ProjectsTabbed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Habilidades.
        /// </summary>
        internal static string SkillsTabbed {
            get {
                return ResourceManager.GetString("SkillsTabbed", resourceCulture);
            }
        }
    }
}
